name: Check Configuration

on:
  push:
    branches:
      - master

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: kpucynski/action-ha-config-check@master
        with:
          ha_version: "latest"
        env:
          HASS_EXTRA_ARGS: "-f -i"
          CONFIG_PATH: "config/"