name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
            ref: ha
            fetch-depth: 1
      - run: |
          git config user.name "$(git log -1 --pretty=format:'%an')"
          git config user.email "$(git log -1 --pretty=format:'%ae')"
          git fetch origin master
          git merge origin/master
          mv config/* .
          rm -rf *.md config
          git add -u
          git add *.yaml
          git commit --amend -m "$(git log -1 --pretty=%B)"
          git push
